import { chromium } from 'playwright';
const URL='https://pickle-stack-app.vercel.app/';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']});
await context.addInitScript(()=>{window.__nativeShareAvailable=typeof Navigator.prototype.share==='function';window.__shared=null;Object.defineProperty(Navigator.prototype,'share',{configurable:true,value:async d=>{window.__shared={url:d?.url||'',hasFiles:!!d?.files?.length,fileName:d?.files?.[0]?.name||''}}});Object.defineProperty(Navigator.prototype,'canShare',{configurable:true,value:d=>!!d?.files?.length});});
const page=await context.newPage();
const check=async(n,f)=>{try{await f();console.log('PASS',n)}catch(e){console.error('FAIL',n);throw e}};
await page.goto(URL,{waitUntil:'networkidle'});await page.evaluate(()=>localStorage.clear());await page.reload({waitUntil:'networkidle'});
await check('production loads',async()=>await page.getByRole('heading',{name:/PickleStack/i}).first().waitFor());
for(const n of ['Ana','Ben','Cara','Dan']){await page.locator('#pn').fill(n);await page.locator('#f').press('Enter')}
await check('four players queued',async()=>{if(await page.locator('#ql li').count()!==4)throw Error('expected 4')});
await page.getByRole('button',{name:/SEND NEXT 4 TO COURT/i}).click();
await check('match starts',async()=>await page.getByText('LIVE',{exact:true}).first().waitFor());
await page.getByRole('button',{name:/Live link/i}).click();
await check('live popup',async()=>{await page.getByText('Live session',{exact:true}).waitFor();await page.getByRole('button',{name:'Copy link'}).waitFor();await page.getByRole('button',{name:'Share'}).waitFor();await page.locator('.qrb svg').waitFor()});
const liveUrl=await page.locator('.break-all').first().innerText();await page.getByRole('button',{name:'Copy link'}).click();
await check('live clipboard',async()=>{if(await page.evaluate(()=>navigator.clipboard.readText())!==liveUrl)throw Error('clipboard mismatch')});
await page.getByRole('button',{name:'Share'}).click();await check('live share wiring',async()=>{const x=await page.evaluate(()=>window.__shared);if(x?.url!==liveUrl)throw Error('share mismatch')});
await page.getByRole('button',{name:'Close'}).click();await page.getByRole('button',{name:/End session/i}).click();await page.getByRole('button',{name:'Confirm'}).click();
await check('permanent end results',async()=>{await page.getByText('Session Results',{exact:true}).waitFor();if(await page.getByRole('button',{name:/Back to session/i}).count())throw Error('Back to session exists');await page.getByRole('button',{name:/Share results image/i}).waitFor()});
const resultsUrl=await page.locator('.break-all').last().innerText();await page.getByRole('button',{name:'Copy results link'}).click();await check('results clipboard',async()=>{if(await page.evaluate(()=>navigator.clipboard.readText())!==resultsUrl)throw Error('results clipboard mismatch')});
await page.getByRole('button',{name:/Share results image/i}).click();await check('results image share wiring',async()=>{const x=await page.evaluate(()=>window.__shared);if(!x?.hasFiles||x.fileName!=='picklestack-results.png')throw Error('image share mismatch')});
await check('old live link final',async()=>{const p=await context.newPage();await p.goto(liveUrl,{waitUntil:'networkidle'});await p.getByText('Final Results',{exact:true}).waitFor({timeout:15000});await p.close()});
await check('results survive refresh',async()=>{await page.reload({waitUntil:'networkidle'});await page.getByText('Session Results',{exact:true}).waitFor()});
console.log('INFO native navigator.share in CI Chromium:',await page.evaluate(()=>window.__nativeShareAvailable));
console.log('INFO viewport:',await page.evaluate(()=>`${innerWidth}x${innerHeight}`));
await browser.close();